version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: aa-ek-postgres
    environment:
      POSTGRES_DB: quarkusdb
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Din Quarkus app (kommer senere)
  # backend:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge